export const SANDBOX_API_KEY = process.env.REACT_APP_INTRINO_SANDBOX_API_KEY
export const SANDBOX_PUBLIC_API_KEY =
  process.env.REACT_APP_INTRINO_SANDBOX_PUBLIC_API_KEY
export const WORLD_TRADING_DATA_API_KEY =
  process.env.REACT_APP_WORLD_TRADING_DATA_API_KEY
